AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal S3 Bucket Demo - Successfully Deployed with Enhanced CFN MCP Server'

Parameters:
  BucketName:
    Type: String
    Description: 'Name for the S3 bucket (must be globally unique)'
    Default: 'cfn-mcp-demo-success-2025'

Resources:
  # Simple S3 Bucket with basic security
  DemoS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Purpose
          Value: 'CFN MCP Server Demo'
        - Key: DeployedBy
          Value: 'Enhanced CloudFormation MCP Server'

  # Simple bucket policy for HTTPS enforcement
  DemoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DemoS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${DemoS3Bucket}/*'
              - !Sub 'arn:aws:s3:::${DemoS3Bucket}'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

Outputs:
  BucketName:
    Description: 'Name of the successfully created S3 bucket'
    Value: !Ref DemoS3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: 'ARN of the created S3 bucket'
    Value: !GetAtt DemoS3Bucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  S3ConsoleUrl:
    Description: 'AWS Console URL for the S3 bucket'
    Value: !Sub 'https://s3.console.aws.amazon.com/s3/buckets/${DemoS3Bucket}?region=${AWS::Region}'

  SuccessMessage:
    Description: 'Deployment success confirmation'
    Value: '✅ CloudFormation template successfully deployed using Enhanced CFN MCP Server with auto-troubleshooting and fix capabilities!'
